/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "",
    "aws_cognito_identity_pool_id": "",
    "aws_cognito_region": "",
    "aws_user_pools_id": "",
    "aws_user_pools_web_client_id": "",
    "oauth": {},
    "aws_user_files_s3_bucket": "",
    "aws_user_files_s3_bucket_region": "",
    aws_cloud_logic: 'enable',
    aws_cloud_logic_custom: [{
        id: '',
        name: 'AdminVODAPI',
        description: '',
        endpoint: '',
        region: '',
        paths: ['/'],
    }, {
        id: '',
        name: '',
        description: 'Live Channel Admin APIs',
        endpoint: '',
        region: '',
        paths: ['/'],
    }, {
        id: '',
        name: 'LiveChannelHandler-API-Demo',
        description: '',
        endpoint: '',
        region: '',
        paths: ['/'],
    },
    ],
};


export default awsmobile;
