/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:775ff72d-0b02-47aa-99f1-3f42fdf9ef5f",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_lPm3FAtK8",
    "aws_user_pools_web_client_id": "7nf5vemqatd32l5mg4oceo2cfr",
    "oauth": {},
    "aws_user_files_s3_bucket": "rsivideosolution-upload173311-dev",
    "aws_user_files_s3_bucket_region": "us-west-2",
    aws_cloud_logic: 'enable',
    aws_cloud_logic_custom: [{
        id: 'kccs8cd1ci',
        name: 'AdminVODAPI',
        description: 'VOD Admin APIs',
        endpoint: 'https://kccs8cd1ci.execute-api.us-west-2.amazonaws.com/user',
        region: 'us-west-2',
        paths: ['/'],
    }, {
        id: '11pz449in4',
        name: 'LiveChannelHandler-API',
        description: 'Live Channel Admin APIs',
        endpoint: 'https://11pz449in4.execute-api.us-west-2.amazonaws.com/live',
        region: 'us-west-2',
        paths: ['/'],
    }, {
        id: '2cs3n47log',
        name: 'LiveChannelHandler-API-Demo',
        description: 'Live Channel Admin Demo APIs',
        endpoint: 'https://2cs3n47log.execute-api.us-west-2.amazonaws.com/live',
        region: 'us-west-2',
        paths: ['/'],
    },
    ],
};


export default awsmobile;
